### ISSUE TITLE
能不能去掉英文，只留下中文？

### ISSUE THREAD

**Issue by skyline75489** [DaiYue/iOS-good-practices-in-Chinese#2]
感觉中英混在一起挺不好读的

**Comment by dopcn** [comment]
@skyline75489 这是一篇用于校对的底稿所以没有去掉

**Comment by DaiYue** [comment]
Hi @skyline75489，谢谢关注~ 之前因为要麻烦 @dopcn 进行校对，所以留下了英文。现在已经完成了校对，并调好了格式，所以只剩下中文了~ 这要感谢 @dopcn @dukuzu 的校对和排版：）
