### ISSUE TITLE
为什么 storyboard 那一节变英文了

### ISSUE THREAD

**Issue by dopcn** [DaiYue/iOS-good-practices-in-Chinese#4]
这一节后半段
https://github.com/DaiYue/iOS-good-practices-in-Chinese#%E7%94%A8-storyboard-%E7%94%BB%E7%95%8C%E9%9D%A2%E6%9C%89%E5%93%AA%E4%BA%9B%E5%A5%BD%E5%A4%84

**Comment by doctor-TZ** [comment]
需要把它删掉,怎么处理?还需要先fork再commit吗?

原始邮件
发件人:Weizhounotifications@github.com
收件人:DaiYue/iOS-good-practices-in-ChineseiOS-good-practices-in-Chinese@noreply.github.com
发送时间:2015年3月30日(周一) 09:45
主题:[iOS-good-practices-in-Chinese] 为什么 storyboard 那一节变英文了 (#4)

这一节后半段
 https://github.com/DaiYue/iOS-good-practices-in-Chinese#%E7%94%A8-storyboard-%E7%94%BB%E7%95%8C%E9%9D%A2%E6%9C%89%E5%93%AA%E4%BA%9B%E5%A5%BD%E5%A4%84

**Comment by dopcn** [comment]
@dukuzu 你上次改的时候改成英文了吗，我只是大概看了一下没有注意，如果你已经 fork 过了直接在你的库提交新的 commit 就行

**Comment by doctor-TZ** [comment]
好的

原始邮件
发件人:Weizhounotifications@github.com
收件人:DaiYue/iOS-good-practices-in-ChineseiOS-good-practices-in-Chinese@noreply.github.com
抄送:and make things better" djkyzy_111@qq.com
发送时间:2015年3月30日(周一) 12:56
主题:Re: [iOS-good-practices-in-Chinese] 为什么 storyboard 那一节变英文了 (#4)

@dukuzu 你上次改的时候改成英文了吗，我只是大概看了一下没有注意，如果你已经 fork 过了直接在你的库提交新的 commit 就行

**Comment by DaiYue** [comment]
@dukuzu 不是后半截变成了英文，是中英对照的英文没删除。前半截的中文和后半截的英文内容是相同的~ 我已经改了并commit了哈：）
